### ISSUE TITLE
Switch to big endian?

### ISSUE THREAD

**Issue by nazar-pc** [grandinetech/rust-kzg#265]
@ArtiomTr you pushed https://github.com/grandinetech/rust-kzg/commit/3d0b8499f74b1ad83a99c88fb770afb210aee09e#diff-0d5371bff0db1d54cd1fda4827c9bab8b1dd4ba41ca77699c0d47a9420b280f3R62 where you have changed little-endian encoding to big-endian encoding, which broke a bunch of assumptions in our downstream project.

There was no PR and no explanation given, why would you possibly do that all of a sudden?

**Comment by nazar-pc** [comment]
I suspect it is related to https://github.com/ethereum/c-kzg-4844/pull/305 and discussions linked from there? If so please create PR and include proper description next time to avoid such surprises.

**Comment by ArtiomTr** [comment]
Hello, yeah, we try to follow c-kzg-4844 implementation. I agree, there should be a better way to document changes - perhaps, having a CHANGELOG.md, or documenting changes in GitHub releases (we should discuss this with @sauliusgrigaitis).

Regarding encoding migration - what issues this caused in your project? Is it caused by `from_bytes`/`to_bytes` functions? Maybe they should have more descriptive names, like in rust std - [`from_be_bytes`](https://doc.rust-lang.org/std/primitive.u32.html#method.from_be_bytes)/[`from_le_bytes`](https://doc.rust-lang.org/std/primitive.u32.html#method.from_le_bytes)

**Comment by nazar-pc** [comment]
Even proper commit message would be helpful in understanding the changes.

It is caused by `from_bytes` and `to_bytes` implementations indeed. We have assumption of the data layout in a few places in our codebase, so after upgrade we started to hit "Invalid scalar" right away. For now I copy-pasted little-endian implementations of those methods into our codebase and we'll try to switch to big-endian before hitting mainnet.

In case it wasn't obvious, we're not implementing Ethereum, just sharing some of the cryptography primitives.
